# Generated by Django 5.0.3 on 2024-05-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="response",
            field=models.CharField(
                blank=True,
                choices=[("JSON", "JSON"), ("XML", "XML")],
                default="JSON",
                max_length=10,
            ),
        ),
    ]
