# Generated by Django 5.0.3 on 2024-05-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.CharField(
                default="", help_text="The actors in the movie.", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(
                default="", help_text="The director of the movie.", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="runtime",
            field=models.CharField(
                default="", help_text="The duration of the movie.", max_length=255
            ),
            preserve_default=False,
        ),
    ]
