# Generated by Django 5.0.3 on 2024-05-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0002_movie_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(
                blank=True, help_text="The date the movie was released.", null=True
            ),
        ),
    ]
