name: Deployment Notifications

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on deployment status
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo "Deployment failed. Take action!"
          echo "Sending email notification..."
          echo "Subject: Deployment failed" | mail -s "Deployment failed" doku_isv@icloud.com
      - name: Notify on successful deployment
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          echo "Deployment successful."
          echo "Sending email notification..."
          echo "Subject: Deployment successful" | mail -s "Deployment successful" doku_isv@icloud.com
